### ISSUE TITLE
struct.error: argument for 's' must be a bytes object

### ISSUE THREAD

**Issue by Ikramromdhani** [plietar/dfuse-tool#11]
I want to build a dfu file from 2 binaries, i tried the build option: `python dfu-convert -b [address:path1, address:path2] -D vid:pid outfile.dfu`.
But when i tried that i got this error:
`Traceback (most recent call last):
  File "dfu-convert", line 143, in <module>
    build ( outfile, [target], device )
  File "dfu-convert", line 75, in build
    tdata=struct.pack ( '<6s2Is2I', 'Target', 0, 1, 'ST...', len ( tdata ), len ( target ) ) + tdata
struct.error: argument for 's' must be a bytes object`
Am i using the build option in a wrong way??

**Comment by Ikramromdhani** [comment]
> I want to build a dfu file from 2 binaries, i tried the build option: `python dfu-convert -b [address:path1, address:path2] -D vid:pid outfile.dfu`.
> But when i tried that i got this error:
> `Traceback (most recent call last): File "dfu-convert", line 143, in <module> build ( outfile, [target], device ) File "dfu-convert", line 75, in build tdata=struct.pack ( '<6s2Is2I', 'Target', 0, 1, 'ST...', len ( tdata ), len ( target ) ) + tdata struct.error: argument for 's' must be a bytes object`
> Am i using the build option in a wrong way??

It is solved by converting all strings into byte type: 
`tdata=struct.pack ( '<6s2Is2I', b'Target', 0, 1, b'ST...', len ( tdata ), len ( target ) ) + tdata`
